#!/usr/bin/env node
import fs from 'fs/promises';
import path from 'path';

const repoRoot = path.resolve('.');
const tokensPath = path.join(repoRoot, 'src', 'lib', 'tokens', 'tokens.v1.json');
const themesPath = path.join(repoRoot, 'src', 'lib', 'tokens', 'themes.v1.json');
const outDir = path.join(repoRoot, 'src', 'styles', 'generated');
const outFile = path.join(outDir, 'tokens.css');

function cssVarName(id) {
  return `--${id.split('.').join('-')}`;
}

function safeString(v) {
  if (v === null || v === undefined) return null;
  return String(v);
}

async function main() {
  try {
    const [tokensRaw, themesRaw] = await Promise.all([
      fs.readFile(tokensPath, 'utf8'),
      fs.readFile(themesPath, 'utf8')
    ]);

    const tokensJson = JSON.parse(tokensRaw);
    const themesJson = JSON.parse(themesRaw);

    const tokensArr = Array.isArray(tokensJson.tokens) ? tokensJson.tokens : [];
    const tokenMap = new Map(tokensArr.map(t => [t.id, t]));

    // collect ids from tokens + themes
    const ids = new Set();
    for (const id of tokenMap.keys()) ids.add(id);
    if (themesJson.modes) {
      for (const mode of Object.keys(themesJson.modes)) {
        const contrasts = themesJson.modes[mode] || {};
        for (const contrast of Object.keys(contrasts)) {
          const map = contrasts[contrast] || {};
          for (const id of Object.keys(map)) ids.add(id);
        }
      }
    }

    const tokenIds = Array.from(ids).sort((a, b) => a.localeCompare(b, undefined, {sensitivity: 'base'}));

    function rootValue(id) {
      const t = tokenMap.get(id);
      if (t && t.value !== undefined) return safeString(t.value);
      const lightDefault = themesJson.modes?.light?.default?.[id];
      if (lightDefault !== undefined) return safeString(lightDefault);
      if (t && t.type) {
        if (t.type === 'color') return 'transparent';
        if (t.type === 'space' || t.type === 'radius') return '0px';
        if (t.type === 'font') return 'inherit';
        if (t.type === 'motion') return '0ms';
      }
      return 'initial';
    }

    function themeValue(mode, contrast, id) {
      return safeString(themesJson.modes?.[mode]?.[contrast]?.[id] ?? null);
    }

    const out = [];
    out.push('/* DO NOT EDIT — generated by scripts/tokens/generate-css.mjs */');
    out.push('');

    // :root
    out.push(':root {');
    for (const id of tokenIds) {
      const v = rootValue(id);
      if (v !== null) out.push(`  ${cssVarName(id)}: ${v};`);
    }
    out.push('}');
    out.push('');

    // dark default overrides
    const darkOverrides = [];
    for (const id of tokenIds) {
      const v = themeValue('dark', 'default', id);
      if (v !== null) {
        const r = rootValue(id);
        if (String(r) !== String(v)) darkOverrides.push(`  ${cssVarName(id)}: ${v};`);
      }
    }
    if (darkOverrides.length) {
      out.push('[data-theme="dark"] {');
      out.push(...darkOverrides);
      out.push('}');
      out.push('');
    }

    // light high contrast overrides
    const lightHigh = [];
    for (const id of tokenIds) {
      const v = themeValue('light', 'high', id);
      if (v !== null) {
        const r = rootValue(id);
        if (String(r) !== String(v)) lightHigh.push(`  ${cssVarName(id)}: ${v};`);
      }
    }
    if (lightHigh.length) {
      out.push('[data-theme="light"][data-contrast="high"] {');
      out.push(...lightHigh);
      out.push('}');
      out.push('');
    }

    // dark high contrast overrides
    const darkHigh = [];
    for (const id of tokenIds) {
      const v = themeValue('dark', 'high', id);
      if (v !== null) {
        const base = themeValue('dark', 'default', id) ?? rootValue(id);
        if (String(base) !== String(v)) darkHigh.push(`  ${cssVarName(id)}: ${v};`);
      }
    }
    if (darkHigh.length) {
      out.push('[data-theme="dark"][data-contrast="high"] {');
      out.push(...darkHigh);
      out.push('}');
      out.push('');
    }

    await fs.mkdir(outDir, { recursive: true });
    await fs.writeFile(outFile, out.join('\n') + '\n', 'utf8');
    console.log('Generated', outFile);
  } catch (err) {
    console.error(err);
    process.exit(1);
  }
}

main();
